apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-postgres-deployment
  template:
    metadata:
      labels:
        app: authentication-postgres-deployment
    spec:
      containers:
      - name: authentication-postgres
        image: charankavali23/authentication-postgres
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "root"
        ports:
        - containerPort: 5432
